-- Generated by Mocodo 4.2.8

CREATE TABLE avis (
  PRIMARY KEY (id_work, id_user),
  id_work   INTEGER unsigned NOT NULL,
  id_user   INTEGER NOT NULL,
  statut    tinyint(1),
  critique  varchar(1000),
  note      INTEGER,
  date_avis DATETIME
);

CREATE TABLE ban (
  PRIMARY KEY (id_ban),
  id_ban     INTEGER NOT NULL,
  definitif  tinyint(1),
  date_ban   datetime,
  date_deban datetime,
  raison     varchar(100),
  id_user    INTEGER UNIQUE,
  probleme   INTEGER
);

CREATE TABLE captcha (
  PRIMARY KEY (id_captcha),
  id_captcha INTEGER NOT NULL AUTO_INCREMENT,
  question   varchar(150)
);

CREATE TABLE administration_captcha (
  PRIMARY KEY (id_user, id_captcha),
  id_user    INTEGER NOT NULL,
  id_captcha INTEGER NOT NULL
);

CREATE TABLE correspondance_captcha (
  PRIMARY KEY (id_captcha, id_reponse),
  id_captcha INTEGER NOT NULL,
  id_reponse INTEGER NOT NULL
);

CREATE TABLE contenu (
  PRIMARY KEY (id_bloc),
  id_bloc      INTEGER NOT NULL AUTO_INCREMENT,
  page_appartenance varchar(100),
  titre        varchar(1000),
  corps        varchar(100),
  last_titre   varchar(100),
  last_corps   varchar(1000)

);

CREATE TABLE administration_contenu (
  PRIMARY KEY (id_user, id_bloc),
  id_user  INTEGER NOT NULL,
  id_bloc  INTEGER NOT NULL,
  date_maj datetime
);

CREATE TABLE demande_ami (
  PRIMARY KEY (envoyeur, receveur),
  envoyeur      INTEGER NOT NULL,
  receveur      INTEGER NOT NULL,
  statut_demande varchar(42),
  date_demande   datetime
);

CREATE TABLE ami (
  id_user_1  INTEGER NOT NULL,
  id_user_2  INTEGER NOT NULL,
  date_amitié datetime
);


CREATE TABLE elements_listes (
  PRIMARY KEY (id_liste, id_work),
  id_liste   INTEGER NOT NULL,
  id_work    INTEGER unsigned NOT NULL,
  date_ajout datetime
);

CREATE TABLE messages (
  PRIMARY KEY (id),
  id INTEGER NOT NULL AUTO_INCREMENT,
  id_user_1       INTEGER NOT NULL,
  id_user_2       INTEGER NOT NULL,
  contenu_message VARCHAR(1000),
  date_messsage   datetime
);

CREATE TABLE listes (
  PRIMARY KEY (id_liste),
  id_liste             INTEGER NOT NULL,
  date_creation        datetime,
  commentaire          varchar(250),
  statut               varchar(42),
  id_user              INTEGER NOT NULL UNIQUE
);

CREATE TABLE logs (
  PRIMARY KEY (id_log),
  id_log         INTEGER NOT NULL AUTO_INCREMENT,
  date_log           datetime,
  log_action    varchar(100),
  adresse_ip     varchar(42)
);

CREATE TABLE consultation_logs (
  PRIMARY KEY (id_user, id_log),
  id_user INTEGER NOT NULL,
  id_log  INTEGER NOT NULL
);

CREATE TABLE recommandation (
  PRIMARY KEY (id_user,id_work),
  id_user INTEGER NOT NULL,
  id_work INTEGER unsigned NOT NULL,
  type_action  varchar(50)
  genre_1                                     varchar(100),
  genre_2                                     varchar(100),
  genre_3                                     varchar(100),
  annee                                      INTEGER,
  origine                                    varchar(3),
  actor_1                                     varchar(100),
  actor_2                                     varchar(100),
  actress_1                                   varchar(100),
  actress_2                                   varchar(100),
  director_1                                  varchar(100),
  director_2                                  varchar(100),
  writer_1                                    varchar(100),
  writer_2                                    varchar(100),
  composer                                   varchar(100),
);


CREATE TABLE reponses_questionnaire (
  PRIMARY KEY (id_reponse),
  id_reponse     INTEGER NOT NULL,
  date           datetime,
  corps_question varchar(1000),
  corps_reponse  varchar(1000),
  id_user        INTEGER NOT NULL
);

CREATE TABLE reponse_captcha (
  PRIMARY KEY (id_reponse),
  id_reponse    INTEGER NOT NULL AUTO_INCREMENT,
  contenu       varchar(150),
  bonne_reponse tinyint(1)
);

CREATE TABLE utilisateur (
  PRIMARY KEY (id_user),
  id_user            INTEGER NOT NULL AUTO_INCREMENT,
  role_user               varchar(50),
  nom                varchar(100),
  prenom             varchar(100),
  date_naissance     date,
  sexe              varchar(50),
  pseudo              varchar(100),
  mail               varchar(150) UNIQUE,
  mdp                char(72),
  date_inscription   datetime,
  photo_utilisateur  varchar(300),
  statut_newsletter  tinyint(1),
  moyenne_age_ami    float,
  majorite_genre_ami varchar(50),
  supprime          tinyint(1),
  verification_code char(6),
  telephone varchar(15)
);

ALTER TABLE avis ADD FOREIGN KEY (id_work) REFERENCES work_basics (id_work);
ALTER TABLE avis ADD FOREIGN KEY (id_user) REFERENCES utilisateur (id_user);

ALTER TABLE ban ADD FOREIGN KEY (id_user) REFERENCES utilisateur (id_user);

ALTER TABLE administration_captcha ADD FOREIGN KEY (id_captcha) REFERENCES captcha (id_captcha);
ALTER TABLE administration_captcha ADD FOREIGN KEY (id_user) REFERENCES utilisateur (id_user);

ALTER TABLE correspondance_captcha ADD FOREIGN KEY (id_reponse) REFERENCES reponse_captcha (id_reponse);
ALTER TABLE correspondance_captcha ADD FOREIGN KEY (id_captcha) REFERENCES captcha (id_captcha);

ALTER TABLE administration_contenu ADD FOREIGN KEY (id_bloc) REFERENCES contenu (id_bloc);
ALTER TABLE administration_contenu ADD FOREIGN KEY (id_user) REFERENCES utilisateur (id_user);

ALTER TABLE demande_ami ADD FOREIGN KEY (receveur) REFERENCES utilisateur (id_user);
ALTER TABLE demande_ami ADD FOREIGN KEY (envoyeur) REFERENCES utilisateur (id_user);

ALTER TABLE ami ADD FOREIGN KEY (receveur) REFERENCES utilisateur (id_user);
ALTER TABLE ami ADD FOREIGN KEY (envoyeur) REFERENCES utilisateur (id_user);

ALTER TABLE elements_listes ADD FOREIGN KEY (id_work) REFERENCES work_basics (id_work);
ALTER TABLE elements_listes ADD FOREIGN KEY (id_liste) REFERENCES listes (id_liste);

ALTER TABLE messages ADD FOREIGN KEY (id_user_2) REFERENCES utilisateur (id_user);
ALTER TABLE messages ADD FOREIGN KEY (id_user_1) REFERENCES utilisateur (id_user);

ALTER TABLE listes ADD FOREIGN KEY (id_user) REFERENCES utilisateur (id_user);

ALTER TABLE consultation_logs ADD FOREIGN KEY (id_log) REFERENCES logs (id_log);
ALTER TABLE consultation_logs ADD FOREIGN KEY (id_user) REFERENCES utilisateur (id_user);

ALTER TABLE recommandation ADD FOREIGN KEY (id_work) REFERENCES work_basics (id_work);
ALTER TABLE recommandation ADD FOREIGN KEY (id_user) REFERENCES utilisateur (id_user);

ALTER TABLE reponses_questionnaire ADD FOREIGN KEY (id_user) REFERENCES utilisateur (id_user);
